[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zomboid_rcon"
version = "2.2.0"
description = "Python class for interacting with Project Zomboid servers using RCON"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Jack Whitworth", email = "jack@jackwhitworth.com" }]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: GNU General Public License (GPL)',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]
keywords = [
    'project-zomboid',
    'rcon',
    'project-zomboid-rcon'
]
dependencies = [
    "rcon >= 2.4.9",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = []

[project.urls]
Homepage = "https://github.com/jmwhitworth/zomboid_rcon"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]
